# STRICT RULES - Prevent LLMs from accumulating dead code and type safety issues
# Philosophy: Block dead code accumulation, warn on type safety, allow API flexibility

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | build
  | dist
  | \.egg-info
)/
'''

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true

# Pragmatic type checking - allow flexibility for public API
disallow_untyped_defs = false
ignore_missing_imports = true

# Strict checks that don't conflict with API flexibility
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
